---
apiVersion: v1
kind: Service
metadata:
  name: hostname-nodeport

spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 80
      name: http
  selector:
    app: hostname
        
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname
  labels:
    app: hostname
spec:
    
  replicas: 4
  selector:
    matchLabels:
      app: hostname
  template:
    
    
    metadata:
      labels:
        app: hostname
            
    spec:
    
      containers:
      
        - name: hostname-pod
          image: fujikomalan/pod:v1
          ports:
            - containerPort: 80
